#!/bin/bash
docker build backend -t registry.socek.org/iep-backend:0.0.${BUILD_NUMBER}
docker build frontend -t registry.socek.org/iep-frontend:0.0.${BUILD_NUMBER}

docker push registry.socek.org/iep-backend:0.0.${BUILD_NUMBER}
docker push registry.socek.org/iep-frontend:0.0.${BUILD_NUMBER}
