#!/bin/bash
set -x
VERSION="$1"
docker build backend -t registry.socek.org/iep-backend:$VERSION
ER=$?
if [ "$ER" != "0" ] ; then
    exit $ER
fi
docker build frontend -t registry.socek.org/iep-frontend:$VERSION
ER=$?
if [ "$ER" != "0" ] ; then
    exit $ER
fi

docker push registry.socek.org/iep-backend:$VERSION
ER=$?
if [ "$ER" != "0" ] ; then
    exit $ER
fi
docker push registry.socek.org/iep-frontend:$VERSION
ER=$?
if [ "$ER" != "0" ] ; then
    exit $ER
fi
