"""empty message

Revision ID: 1ed270fe6feb
Revises: 4523dfa165a8
Create Date: 2019-05-05 18:31:22.478772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed270fe6feb'
down_revision = '4523dfa165a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'accepted')
    # ### end Alembic commands ###
