"""empty message

Revision ID: 4523dfa165a8
Revises: fad1e5ea7f13
Create Date: 2019-04-28 10:55:22.248598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4523dfa165a8'
down_revision = 'fad1e5ea7f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('room', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'room')
    # ### end Alembic commands ###
