"""empty message

Revision ID: 4c296cf8919d
Revises: 5937990364a8
Create Date: 2019-06-27 21:01:45.698042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c296cf8919d'
down_revision = '5937990364a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('convention_uid', table_name='panel_times')
    op.create_index('convention_uid', 'panel_times', ['panel_uid'], unique=False)
    op.drop_constraint('uq_panel_times_convention_uid', 'panel_times', type_='unique')
    op.create_unique_constraint(op.f('uq_panel_times_convention_uid'), 'panel_times', ['convention_uid', 'panel_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_panel_times_convention_uid'), 'panel_times', type_='unique')
    op.create_unique_constraint('uq_panel_times_convention_uid', 'panel_times', ['convention_uid', 'panel_uid', 'room_uid'])
    op.drop_index('convention_uid', table_name='panel_times')
    op.create_index('convention_uid', 'panel_times', ['panel_uid', 'room_uid'], unique=False)
    # ### end Alembic commands ###
