"""empty message

Revision ID: 5937990364a8
Revises: ecfc7daa95bb
Create Date: 2019-06-24 20:00:33.857875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5937990364a8'
down_revision = 'ecfc7daa95bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('convention_uid', 'panel_times', ['panel_uid', 'room_uid'], unique=False)
    op.create_unique_constraint(op.f('uq_panel_times_convention_uid'), 'panel_times', ['convention_uid', 'panel_uid', 'room_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_panel_times_convention_uid'), 'panel_times', type_='unique')
    op.drop_index('convention_uid', table_name='panel_times')
    # ### end Alembic commands ###
