"""empty message

Revision ID: 5eeb5e0a954f
Revises: bfbaf8ecddb4
Create Date: 2019-05-20 20:07:46.266925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5eeb5e0a954f'
down_revision = 'bfbaf8ecddb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_times',
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('convention_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('panel_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convention_uid'], ['conventions.uid'], name=op.f('fk_panel_times_convention_uid_conventions')),
    sa.ForeignKeyConstraint(['panel_uid'], ['panels.uid'], name=op.f('fk_panel_times_panel_uid_panels')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_panel_times'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_times')
    # ### end Alembic commands ###
