"""empty message

Revision ID: 63df8d50292d
Revises: 4fef43733470
Create Date: 2019-07-08 19:03:37.770934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63df8d50292d'
down_revision = '4fef43733470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest2panels',
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('convention_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('guest_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('panel_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['convention_uid'], ['conventions.uid'], name=op.f('fk_guest2panels_convention_uid_conventions')),
    sa.ForeignKeyConstraint(['guest_uid'], ['guests.uid'], name=op.f('fk_guest2panels_guest_uid_guests')),
    sa.ForeignKeyConstraint(['panel_uid'], ['panels.uid'], name=op.f('fk_guest2panels_panel_uid_panels')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_guest2panels'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest2panels')
    # ### end Alembic commands ###
