"""empty message

Revision ID: bfbaf8ecddb4
Revises: 3a38fc4b89a0
Create Date: 2019-05-13 20:16:34.075673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfbaf8ecddb4'
down_revision = '3a38fc4b89a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('convention_uid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_panels_convention_uid_conventions'), 'panels', 'conventions', ['convention_uid'], ['uid'])
    op.add_column('rooms', sa.Column('convention_uid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_rooms_convention_uid_conventions'), 'rooms', 'conventions', ['convention_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rooms_convention_uid_conventions'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'convention_uid')
    op.drop_constraint(op.f('fk_panels_convention_uid_conventions'), 'panels', type_='foreignkey')
    op.drop_column('panels', 'convention_uid')
    # ### end Alembic commands ###
