"""empty message

Revision ID: f840c1fabbae
Revises: 5eeb5e0a954f
Create Date: 2019-05-20 20:19:38.173157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f840c1fabbae'
down_revision = '5eeb5e0a954f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_times', sa.Column('room_uid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_panel_times_room_uid_rooms'), 'panel_times', 'rooms', ['room_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_panel_times_room_uid_rooms'), 'panel_times', type_='foreignkey')
    op.drop_column('panel_times', 'room_uid')
    # ### end Alembic commands ###
