"""empty message

Revision ID: fad1e5ea7f13
Revises: 1a9cfc369c4f
Create Date: 2019-04-28 07:30:17.982617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fad1e5ea7f13'
down_revision = '1a9cfc369c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panels',
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('additional', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_panels'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panels')
    # ### end Alembic commands ###
